

export const ERRORS = {
  EMAIL_ALREADY_INVITED: 'EMAIL_ALREADY_INVITED',
  INVITE_TOKEN_INVALID: 'INVITE_TOKEN_INVALID',
  PHONE_NUMBER_EXISTS: 'PHONE_NUMBER_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  USER_RECENTLY_INVITED: 'USER_RECENTLY_INVITED',
};