export const EXPENSES_TABLE_STATE_SET = 'EXPENSES/TABLE_STATE_SET' as const;
export const EXPENSES_TABLE_STATE_RESET = 'EXPENSES/TABLE_STATE_RESET' as const;
export const EXPENSES_SET_SELECTED_ROWS = 'EXPENSES/SET_SELECTED_ROWS' as const;
