export const ERRORS = {
  TAX_RATE_NOT_FOUND: 'TAX_RATE_NOT_FOUND',
  TAX_CODE_NOT_UNIQUE: 'TAX_CODE_NOT_UNIQUE',
  ITEM_ENTRY_TAX_RATE_CODE_NOT_FOUND: 'ITEM_ENTRY_TAX_RATE_CODE_NOT_FOUND',
  ITEM_ENTRY_TAX_RATE_ID_NOT_FOUND: 'ITEM_ENTRY_TAX_RATE_ID_NOT_FOUND',
  TAX_RATE_ALREADY_ACTIVE: 'TAX_RATE_ALREADY_ACTIVE',
  TAX_RATE_ALREADY_INACTIVE: 'TAX_RATE_ALREADY_INACTIVE'
};
