export const ESTIMATES_TABLE_STATE_SET = 'ESTIMATES/TABLE_STATE_SET' as const;
export const ESTIMATES_TABLE_STATE_RESET = 'ESTIMATES/TABLE_STATE_RESET' as const;
export const ESTIMATES_SET_SELECTED_ROWS = 'ESTIMATES/SET_SELECTED_ROWS' as const;
