export const VENDOR_CREDITS_TABLE_STATE_SET = 'VENDOR_CREDITS/TABLE_STATE_SET' as const;
export const VENDOR_CREDITS_NOTES_TABLE_STATE_RESET = 'VENDOR_CREDITS/TABLE_STATE_RESET' as const;
export const VENDOR_CREDITS_SET_SELECTED_ROWS = 'VENDOR_CREDITS/SET_SELECTED_ROWS' as const;
