export const ERRORS = {
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PREFINED: 'ROLE_PREFINED',
  INVALIDATE_PERMISSIONS: 'INVALIDATE_PERMISSIONS',
  CANNT_DELETE_ROLE_ASSOCIATED_TO_USERS:
    'CANNT_DELETE_ROLE_ASSOCIATED_TO_USERS',
  CANNOT_GRANT_ROLE: 'CANNOT_GRANT_ROLE',
  CANNOT_REMOVE_LAST_ADMIN: 'CANNOT_REMOVE_LAST_ADMIN',
};
