export const ERRORS = {
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PREFINED: 'ROLE_PREFINED',
  INVALIDATE_PERMISSIONS: 'INVALIDATE_PERMISSIONS',
  CANNT_DELETE_ROLE_ASSOCIATED_TO_USERS: 'CANNT_DELETE_ROLE_ASSOCIATED_TO_USERS'
};
