export const ITEMS_CATEGORIES_TABLE_STATE_SET =
  'ITEMS_CATEGORIES/TABLE_STATE_SET' as const;

export const ITEMS_CATEGORIES_SET_SELECTED_ROWS =
  'ITEMS_CATEGORIES/SET_SELECTED_ROWS' as const;

export const ITEMS_CATEGORIES_RESET_SELECTED_ROWS =
  'ITEMS_CATEGORIES/RESET_SELECTED_ROWS' as const;
