export const ORGANIZATION_SET = 'ORGANIZATION_SET' as const;
export const ORGANIZATIONS_LIST_SET = 'ORGANIZATIONS_LIST_SET' as const;
export const SET_ORGANIZATION_CONGRATS = 'SET_ORGANIZATION_CONGRATS' as const;
export const ORGANIZATION_MUTATE_BASE_CURRENCY_ABILITIES = 'ORGANIZATION_MUTATE_BASE_CURRENCY_ABILITIES' as const;
