export default {
  RECEIPT_DELETE: 'RECEIPT_DELETE',
  RECEIPTS_BULK_DELETE: 'RECEIPTS_BULK_DELETE',
  RECEIPTS_LIST_SET: 'RECEIPTS_LIST_SET',
  RECEIPT_SET: 'RECEIPT_SET',
  RECEIPTS_SET_CURRENT_VIEW: 'RECEIPTS_SET_CURRENT_VIEW',
  RECEIPTS_TABLE_QUERIES_ADD: 'RECEIPTS_TABLE_QUERIES_ADD',
  RECEIPTS_TABLE_LOADING: 'RECEIPTS_TABLE_LOADING',
  RECEIPTS_PAGINATION_SET: 'RECEIPTS_PAGINATION_SET',
  RECEIPTS_PAGE_SET: 'RECEIPTS_PAGE_SET',
  RECEIPTS_ITEMS_SET: 'RECEIPTS_ITEMS_SET',
};
