export const INVOICES_TABLE_STATE_SET = 'INVOICES/TABLE_STATE_SET' as const;
export const INVOICES_TABLE_STATE_RESET = 'INVOICES/TABLE_STATE_RESET' as const;
export const INVOICES_SET_SELECTED_ROWS = 'INVOICES/SET_SELECTED_ROWS' as const;
export const INVOICES_RESET_SELECTED_ROWS = 'INVOICES/RESET_SELECTED_ROWS' as const;
