export const ERRORS = {
  INVENTORY_ADJUSTMENT_NOT_FOUND: 'INVENTORY_ADJUSTMENT_NOT_FOUND',
  ITEM_SHOULD_BE_INVENTORY_TYPE: 'ITEM_SHOULD_BE_INVENTORY_TYPE',
  INVENTORY_ADJUSTMENT_ALREADY_PUBLISHED:
    'INVENTORY_ADJUSTMENT_ALREADY_PUBLISHED',
};
