export default {
  VENDORS_ITEMS_SET: 'VENDORS_ITEMS_SET',
  VENDOR_SET: 'VENDOR_SET',
  VENDORS_PAGE_SET: 'VENDORS_PAGE_SET',
  VENDORS_TABLE_LOADING: 'VENDORS_TABLE_LOADING',
  VENDORS_TABLE_QUERIES_ADD: 'VENDORS/TABLE_QUERIES_ADD',
  VENDOR_DELETE: 'VENDOR_DELETE',
  VENDORS_BULK_DELETE: 'VENDORS_BULK_DELETE',
  VENDORS_PAGINATION_SET: 'VENDORS_PAGINATION_SET',
  VENDORS_SET_CURRENT_VIEW: 'VENDORS_SET_CURRENT_VIEW',
  VENDOR_SELECTED_ROWS_SET: 'VENDOR_SELECTED_ROWS_SET',
};
