export const ERRORS = {
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  MULTI_BRANCHES_ALREADY_ACTIVATED: 'MULTI_BRANCHES_ALREADY_ACTIVATED',
  COULD_NOT_DELETE_ONLY_BRANCH: 'COULD_NOT_DELETE_ONLY_BRANCH',
  BRANCH_CODE_NOT_UNIQUE: 'BRANCH_CODE_NOT_UNIQUE',
  BRANCH_HAS_ASSOCIATED_TRANSACTIONS: 'BRANCH_HAS_ASSOCIATED_TRANSACTIONS'
};
