import {
  CreditNoteActivateBranchesSubscriber,
  PaymentMadeActivateBranchesSubscriber,
  PaymentReceiveActivateBranchesSubscriber,
  SaleEstimatesActivateBranchesSubscriber,
  SaleInvoicesActivateBranchesSubscriber,
  SaleReceiptsActivateBranchesSubscriber,
} from './Subscribers/Activate';
import {
  BillBranchValidateSubscriber,
  CashflowBranchDTOValidatorSubscriber,
  ContactBranchValidateSubscriber,
  CreditNoteBranchValidateSubscriber,
  CreditNoteRefundBranchValidateSubscriber,
  ExpenseBranchValidateSubscriber,
  InventoryAdjustmentBranchValidateSubscriber,
  InvoiceBranchValidateSubscriber,
  ManualJournalBranchValidateSubscriber,
  PaymentMadeBranchValidateSubscriber,
  PaymentReceiveBranchValidateSubscriber,
  SaleEstimateBranchValidateSubscriber,
  SaleReceiptBranchValidateSubscriber,
  VendorCreditBranchValidateSubscriber,
  VendorCreditRefundBranchValidateSubscriber,
} from './Subscribers/Validators';

export default () => [
  BillBranchValidateSubscriber,
  CreditNoteBranchValidateSubscriber,
  ExpenseBranchValidateSubscriber,
  PaymentMadeBranchValidateSubscriber,
  SaleReceiptBranchValidateSubscriber,
  VendorCreditBranchValidateSubscriber,
  SaleEstimateBranchValidateSubscriber,
  ManualJournalBranchValidateSubscriber,
  PaymentReceiveBranchValidateSubscriber,
  CreditNoteRefundBranchValidateSubscriber,
  VendorCreditRefundBranchValidateSubscriber,

  CreditNoteActivateBranchesSubscriber,
  PaymentReceiveActivateBranchesSubscriber,
  SaleEstimatesActivateBranchesSubscriber,
  SaleInvoicesActivateBranchesSubscriber,
  PaymentMadeActivateBranchesSubscriber,
  SaleReceiptsActivateBranchesSubscriber,
  CashflowBranchDTOValidatorSubscriber,
  InvoiceBranchValidateSubscriber,
  ContactBranchValidateSubscriber,
  InventoryAdjustmentBranchValidateSubscriber,
];
