export default {
  INVENTORY_ADJUSTMENT_ITEMS_SET: 'INVENTORY_ADJUSTMENT_ITEMS_SET',
  INVENTORY_ADJUSTMENT_DELETE: 'INVENTORY_ADJUSTMENT_DELETE',
  INVENTORY_ADJUSTMENTS_LOADING: 'INVENTORY_ADJUSTMENTS_LOADING',
  INVENTORY_ADJUSTMENTS_PAGE_SET: 'INVENTORY_ADJUSTMENTS_PAGE_SET',

  INVENTORY_ADJUSTMENTS_PAGINATION_SET: 'INVENTORY_ADJUSTMENTS_PAGINATION_SET',


  INVENTORY_ADJUSTMENTS_TABLE_QUERIES_ADD:
    'INVENTORY_ADJUSTMENTS/TABLE_QUERIES_ADD',
  INVENTORY_ADJUSTMENTS_SET_CURRENT_VIEW:
    'INVENTORY_ADJUSTMENTS_SET_CURRENT_VIEW',
};
