export const RECEIPTS_TABLE_STATE_SET = 'RECEIPTS/TABLE_STATE_SET' as const;
export const RECEIPTS_TABLE_STATE_RESET = 'RECEIPTS/TABLE_STATE_RESET' as const;
export const RECEIPTS_SELECTED_ROWS_SET = 'RECEIPTS/SELECTED_ROWS_SET' as const;
