export const AccountsSampleData = [
  {
    'Account Name': 'Utilities Expense',
    'Account Code': 9000,
    Type: 'Expense',
    Description: 'Omnis voluptatum consequatur.',
    Active: 'T',
    'Currency Code': '',
  },
  {
    'Account Name': 'Unearned Revenue',
    'Account Code': 9010,
    Type: 'Long Term Liability',
    Description: 'Autem odit voluptas nihil unde.',
    Active: 'T',
    'Currency Code': '',
  },
  {
    'Account Name': 'Long-Term Debt',
    'Account Code': 9020,
    Type: 'Long Term Liability',
    Description: 'In voluptas cumque exercitationem.',
    Active: 'T',
    'Currency Code': '',
  },
  {
    'Account Name': 'Salaries and Wages Expense',
    'Account Code': 9030,
    Type: 'Expense',
    Description: 'Assumenda aspernatur soluta aliquid perspiciatis quasi.',
    Active: 'T',
    'Currency Code': '',
  },
  {
    'Account Name': 'Rental Income',
    'Account Code': 9040,
    Type: 'Income',
    Description: 'Omnis possimus amet occaecati inventore.',
    Active: 'T',
    'Currency Code': '',
  },
  {
    'Account Name': 'Paypal',
    'Account Code': 9050,
    Type: 'Bank',
    Description: 'In voluptas cumque exercitationem.',
    Active: 'T',
    'Currency Code': '',
  },
];
