export const VendorsSampleData = [
  {
    "First Name": "Nicolette",
    "Last Name": "Schamberger",
    "Company Name": "Homenick - Hane",
    "Display Name": "Rowland Rowe",
    "Email": "cicero86@yahoo.com",
    "Personal Phone Number": "811-603-2235",
    "Work Phone Number": "906-993-5190",
    "Website": "http://google.com",
    "Opening Balance": 54302.23,
    "Opening Balance At": "2022-02-02",
    "Opening Balance Ex. Rate": 2,
    "Currency": "LYD",
    "Active": "T",
    "Note": "Doloribus autem optio temporibus dolores mollitia sit.",
    "Billing Address 1": "862 Jessika Well",
    "Billing Address 2": "1091 Dorthy Mount",
    "Billing Address City": "Deckowfort",
    "Billing Address Country": "Ghana",
    "Billing Address Phone": "825-011-5207",
    "Billing Address Postcode": "38228",
    "Billing Address State": "Oregon",
    "Shipping Address 1": "37626 Thiel Villages",
    "Shipping Address 2": "132 Batz Avenue",
    "Shipping Address City": "Pagacburgh",
    "Shipping Address Country": "Albania",
    "Shipping Address Phone": "171-546-3701",
    "Shipping Address Postcode": "13709",
    "Shipping Address State": "Georgia"
  },
  {
    "First Name": "Hermann",
    "Last Name": "Crooks",
    "Company Name": "Veum - Schaefer",
    "Display Name": "Harley Veum",
    "Email": "immanuel56@hotmail.com",
    "Personal Phone Number": "449-780-9999",
    "Work Phone Number": "970-473-5785",
    "Website": "http://google.com",
    "Opening Balance": 54302.23,
    "Opening Balance At": "2022-02-02",
    "Opening Balance Ex. Rate": 2,
    "Currency": "LYD",
    "Active": "T",
    "Note": "Doloribus dolore dolor dicta vitae in fugit nisi quibusdam.",
    "Billing Address 1": "532 Simonis Spring",
    "Billing Address 2": "3122 Nicolas Inlet",
    "Billing Address City": "East Matteofort",
    "Billing Address Country": "Holy See (Vatican City State)",
    "Billing Address Phone": "366-084-8629",
    "Billing Address Postcode": "41607",
    "Billing Address State": "Montana",
    "Shipping Address 1": "2889 Tremblay Plaza",
    "Shipping Address 2": "71355 Kutch Isle",
    "Shipping Address City": "D'Amorehaven",
    "Shipping Address Country": "Monaco",
    "Shipping Address Phone": "614-189-3328",
    "Shipping Address Postcode": "09634-0435",
    "Shipping Address State": "Nevada"
  },
  {
    "First Name": "Nellie",
    "Last Name": "Gulgowski",
    "Company Name": "Boyle, Heller and Jones",
    "Display Name": "Randall Kohler",
    "Email": "anibal_frami@yahoo.com",
    "Personal Phone Number": "498-578-0740",
    "Work Phone Number": "394-550-6827",
    "Website": "http://google.com",
    "Opening Balance": 54302.23,
    "Opening Balance At": "2022-02-02",
    "Opening Balance Ex. Rate": 2,
    "Currency": "LYD",
    "Active": "T",
    "Note": "Vero quibusdam rem fugit aperiam est modi.",
    "Billing Address 1": "214 Sauer Villages",
    "Billing Address 2": "30687 Kacey Square",
    "Billing Address City": "Jayceborough",
    "Billing Address Country": "Benin",
    "Billing Address Phone": "332-820-1127",
    "Billing Address Postcode": "16425-3887",
    "Billing Address State": "Mississippi",
    "Shipping Address 1": "562 Diamond Loaf",
    "Shipping Address 2": "9595 Satterfield Trafficway",
    "Shipping Address City": "Alexandrinefort",
    "Shipping Address Country": "Puerto Rico",
    "Shipping Address Phone": "776-500-8456",
    "Shipping Address Postcode": "30258",
    "Shipping Address State": "South Dakota"
  },
  {
    "First Name": "Stone",
    "Last Name": "Jerde",
    "Company Name": "Cassin, Casper and Maggio",
    "Display Name": "Clint McLaughlin",
    "Email": "nathanael22@yahoo.com",
    "Personal Phone Number": "562-790-6059",
    "Work Phone Number": "686-838-0027",
    "Website": "http://google.com",
    "Opening Balance": 54302.23,
    "Opening Balance At": "2022-02-02",
    "Opening Balance Ex. Rate": 2,
    "Currency": "LYD",
    "Active": "T",
    "Note": "Quis cumque molestias rerum.",
    "Billing Address 1": "22590 Cathy Harbor",
    "Billing Address 2": "24493 Brycen Brooks",
    "Billing Address City": "Elnorashire",
    "Billing Address Country": "Andorra",
    "Billing Address Phone": "701-852-8005",
    "Billing Address Postcode": "5680",
    "Billing Address State": "Nevada",
    "Shipping Address 1": "5355 Erdman Bridge",
    "Shipping Address 2": "421 Jeanette Camp",
    "Shipping Address City": "East Philip",
    "Shipping Address Country": "Venezuela",
    "Shipping Address Phone": "426-119-0858",
    "Shipping Address Postcode": "34929-0501",
    "Shipping Address State": "Tennessee"
  }
]
