export const WAREHOUSE_TRANSFERS_TABLE_STATE_SET = 'WAREHOUSE_TRANSFERS/TABLE_STATE_SET' as const;
export const WAREHOUSE_TRANSFERS_TABLE_STATE_RESET = 'WAREHOUSE_TRANSFERS/TABLE_STATE_RESET' as const;
