export default {
  ESTIMATES_LIST_SET: 'ESTIMATES_LIST_SET',
  ESTIMATE_SET: 'ESTIMATE_SET',
  ESTIMATE_DELETE: 'ESTIMATE_DELETE',
  ESTIMATES_BULK_DELETE: 'ESTIMATES_BULK_DELETE',
  ESTIMATES_SET_CURRENT_VIEW: 'ESTIMATES_SET_CURRENT_VIEW',
  ESTIMATES_TABLE_QUERIES_ADD: 'ESTIMATES_TABLE_QUERIES_ADD',
  ESTIMATES_TABLE_LOADING: 'ESTIMATES_TABLE_LOADING',
  ESTIMATES_PAGINATION_SET: 'ESTIMATES_PAGINATION_SET',
  ESTIMATES_PAGE_SET: 'ESTIMATES_PAGE_SET',
  ESTIMATES_ITEMS_SET: 'ESTIMATES_ITEMS_SET',
  ESTIMATE_NUMBER_CHANGED: 'ESTIMATE_NUMBER_CHANGED',
};
