export const ERRORS = {
  CANNOT_DELETE_LAST_USER: 'CANNOT_DELETE_LAST_USER',
  USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE: 'USER_ALREADY_INACTIVE',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_NUMBER_ALREADY_EXIST: 'PHONE_NUMBER_ALREADY_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_SAME_THE_AUTHORIZED_USER: 'USER_SAME_THE_AUTHORIZED_USER',
  CANNOT_AUTHORIZED_USER_MUTATE_ROLE: 'CANNOT_AUTHORIZED_USER_MUTATE_ROLE',

  EMAIL_ALREADY_INVITED: 'EMAIL_ALREADY_INVITED',
  INVITE_TOKEN_INVALID: 'INVITE_TOKEN_INVALID',
  PHONE_NUMBER_EXISTS: 'PHONE_NUMBER_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_NOT_EXISTS: 'EMAIL_NOT_EXISTS',
  USER_RECENTLY_INVITED: 'USER_RECENTLY_INVITED',
};

export const SendInviteUserMailQueue = 'SendInviteUserMailQueue';
export const SendInviteUserMailJob = 'SendInviteUserMailJob';
