

export default {
  ACCOUNT_TYPES_LIST_SET: 'ACCOUNT_TYPES_LIST_SET',
  ACCOUNTS_PAGE_SET: 'ACCOUNTS_PAGE_SET',
  ACCOUNTS_ITEMS_SET: 'ACCOUNTS_ITEMS_SET',
  ACCOUNT_SET: 'ACCOUNT_SET',
  ACCOUNT_DELETE: 'ACCOUNT_DELETE',
  ACCOUNT_FORM_ERRORS: 'ACCOUNT_FORM_ERRORS',
  CLEAR_ACCOUNT_FORM_ERRORS: 'CLEAR_ACCOUNT_FORM_ERRORS',

  ACCOUNTS_SELECTED_ROWS_SET: 'ACCOUNTS_SELECTED_ROWS_SET',

  ACCOUNTS_SET_CURRENT_VIEW: 'ACCOUNTS_SET_CURRENT_VIEW',
  
  ACCOUNTS_TABLE_QUERY_SET: 'ACCOUNTS_TABLE_QUERY_SET',
  ACCOUNTS_TABLE_QUERIES_SET: 'ACCOUNTS_TABLE_QUERIES_SET',

  ACCOUNTS_TABLE_LOADING: 'ACCOUNTS_TABLE_LOADING',
};