

export default {
  ACCOUNT_TYPES_LIST_SET: 'ACCOUNT_TYPES_LIST_SET',
  ACCOUNTS_PAGE_SET: 'ACCOUNTS_PAGE_SET',
  ACCOUNTS_ITEMS_SET: 'ACCOUNTS_ITEMS_SET',
  ACCOUNT_SET: 'ACCOUNT_SET',
  ACCOUNT_FORM_ERRORS: 'ACCOUNT_FORM_ERRORS',
  CLEAR_ACCOUNT_FORM_ERRORS: 'CLEAR_ACCOUNT_FORM_ERRORS',

  ACCOUNT_BULK_ACTION_ADD: 'ACCOUNT_BULK_ACTION_ADD',
  ACCOUNT_BULK_ACTION_REMOVE: 'ACCOUNT_BULK_ACTION_REMOVE',

  ACCOUNTS_SET_CURRENT_VIEW: 'ACCOUNTS_SET_CURRENT_VIEW',
};