export default {
  ITEMS_CATEGORY_LIST_SET: 'ITEMS_CATEGORY_LIST_SET',
  ITEMS_CATEGORY_DATA_TABLE: 'ITEMS_CATEGORY_DATA_TABLE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  CLEAR_CATEGORY_FORM_ERRORS: 'CLEAR_CATEGORY_FORM_ERRORS',
  CATEGORY_COUNTER:'CATEGORY_COUNTER'
};
