export default {
  ITEMS_CATEGORY_LIST_SET: 'ITEMS_CATEGORY_LIST_SET',
  ITEMS_CATEGORY_DATA_TABLE: 'ITEMS_CATEGORY_DATA_TABLE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  ITEM_CATEGORIES_TABLE_LOADING: 'ITEM_CATEGORIES_TABLE_LOADING'
};
