export const PAYMENT_MADES_TABLE_STATE_SET =
  'PAYMENT_MADES/TABLE_STATE_SET' as const;
export const PAYMENT_MADES_TABLE_STATE_RESET =
  'PAYMENT_MADES/TABLE_STATE_RESET' as const;
export const PAYMENT_MADES_SET_SELECTED_ROWS =
  'PAYMENT_MADES/SET_SELECTED_ROWS' as const;
export const PAYMENT_MADES_RESET_SELECTED_ROWS =
  'PAYMENT_MADES/RESET_SELECTED_ROWS' as const;
