export const ERRORS = {
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PREDEFINED: 'ROLE_PREDEFINED',
  INVALIDATE_PERMISSIONS: 'INVALIDATE_PERMISSIONS',
  CANNOT_DELETE_ROLE_ASSOCIATED_TO_USERS: 'CANNOT_DELETE_ROLE_ASSOCIATED_TO_USERS'
};
