export const CUSTOMERS_TABLE_STATE_SET = 'CUSTOMERS/TABLE_STATE_SET' as const;
export const CUSTOMERS_TABLE_STATE_RESET = 'CUSTOMERS/TABLE_STATE_RESET' as const;
export const CUSTOMERS_SET_SELECTED_ROWS = 'CUSTOMERS/SET_SELECTED_ROWS' as const;
export const CUSTOMERS_RESET_SELECTED_ROWS = 'CUSTOMERS/RESET_SELECTED_ROWS' as const;
