export default {
  INVOICE_DELETE: 'INVOICE_DELETE',
  INVOICES_BULK_DELETE: 'INVOICES_BULK_DELETE',
  INVOICES_LIST_SET: 'INVOICES_LIST_SET',
  INVOICE_SET: 'INVOICE_SET',
  INVOICES_SET_CURRENT_VIEW: 'INVOICES_SET_CURRENT_VIEW',
  INVOICES_TABLE_QUERIES_ADD: 'INVOICES/TABLE_QUERIES_ADD',
  INVOICES_TABLE_LOADING: 'INVOICES_TABLE_LOADING',
  INVOICES_PAGINATION_SET: 'INVOICES_PAGINATION_SET',
  INVOICES_PAGE_SET: 'INVOICES_PAGE_SET',
  INVOICES_ITEMS_SET: 'INVOICES_ITEMS_SET',
  DUE_INVOICES_SET: 'DUE_INVOICES_SET',
  RELOAD_INVOICES: 'RELOAD_INVOICES',

  INVOICES_RECEIVABLE_BY_PAYMENT_ID: 'INVOICES_RECEIVABLE_BY_PAYMENT_ID',
  INVOICES_RECEIVABLE_BY_CUSTOMER_ID: 'INVOICES_RECEIVABLE_BY_CUSTOMER_ID',
  INVOICES_BY_PAYMENT_ID: 'INVOICES_BY_PAYMENT_ID',

  INVOICE_NUMBER_CHANGED: 'INVOICE_NUMBER_CHANGED',
};
