export const ERRORS = {
  BUDGET_NOT_FOUND: 'BUDGET_NOT_FOUND',
  BUDGET_ACTIVE_CANNOT_EDIT: 'BUDGET_ACTIVE_CANNOT_EDIT',
  BUDGET_CLOSED_CANNOT_EDIT: 'BUDGET_CLOSED_CANNOT_EDIT',
  BUDGET_ACTIVE_CANNOT_DELETE: 'BUDGET_ACTIVE_CANNOT_DELETE',
  BUDGET_CLOSED_CANNOT_DELETE: 'BUDGET_CLOSED_CANNOT_DELETE',
  BUDGET_ALREADY_ACTIVE: 'BUDGET_ALREADY_ACTIVE',
  BUDGET_ALREADY_CLOSED: 'BUDGET_ALREADY_CLOSED',
  BUDGET_DRAFT_ONLY_ACTIVATE: 'BUDGET_DRAFT_ONLY_ACTIVATE',
  BUDGET_ACTIVE_ONLY_CLOSE: 'BUDGET_ACTIVE_ONLY_CLOSE',
  ENTRIES_ACCOUNTS_NOT_FOUND: 'ENTRIES_ACCOUNTS_NOT_FOUND',
  START_DATE_AFTER_END_DATE: 'START_DATE_AFTER_END_DATE',
};
