
export default {
  ORGANIZATIONS_LIST_SET: 'ORGANIZATIONS_LIST_SET',

  SET_ORGANIZATION_SEEDING: 'SET_ORGANIZATION_SEEDING',
  SET_ORGANIZATION_SEEDED: 'SET_ORGANIZATION_SEEDED',

  SET_ORGANIZATION_INITIALIZED: 'SET_ORGANIZATION_INITIALIZED',
  SET_ORGANIZATION_INITIALIZING: 'SET_ORGANIZATION_INITIALIZING',

  SET_ORGANIZATION_CONGRATS: 'SET_ORGANIZATION_CONGRATS'
};