export default {
  ITEMS_SET: 'ITEMS_SET',
  ITEM_SET: 'ITEM_SET',
  ITEMS_PAGE_SET: 'ITEMS_PAGE_SET',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_BULK_ACTION_ADD: 'ITEM_BULK_ACTION_ADD',
  ITEM_BULK_ACTION_REMOVE: 'ITEM_BULK_ACTION_REMOVE',

  ITEMS_TABLE_QUERY_SET: 'ITEMS_TABLE_QUERY_SET',
  ITEMS_TABLE_QUERIES_ADD: 'ITEMS_TABLE_QUERIES_ADD',

  ITEMS_TABLE_LOADING: 'ITEMS_TABLE_LOADING',
  ITEMS_SET_CURRENT_VIEW: 'ITEMS_SET_CURRENT_VIEW',
  ITEMS_BULK_DELETE: 'ITEMS_BULK_DELETE',
};
