

export default {
  ITEMS_SET: 'ITEMS_SET',
  ITEMS_PAGE_SET: 'ITEMS_PAGE_SET',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_BULK_ACTION_ADD: 'ITEM_BULK_ACTION_ADD',
  ITEM_BULK_ACTION_REMOVE: 'ITEM_BULK_ACTION_REMOVE',
}