

export default {
  ITEMS_SET: 'ITEMS_SET',
  ITEMS_PAGE_SET: 'ITEMS_PAGE_SET',
  ITEM_DELETE: 'ITEM_DELETE',
  ITEM_BULK_ACTION_ADD: 'ITEM_BULK_ACTION_ADD',
  ITEM_BULK_ACTION_REMOVE: 'ITEM_BULK_ACTION_REMOVE',

  ITEMS_TABLE_QUERY_SET: 'ITEMS_TABLE_QUERY_SET',
  ITEMS_TABLE_QUERIES_ADD: 'ITEMS_TABLE_QUERIES_ADD',

  ITEMS_TABLE_LOADING: 'ITEMS_TABLE_LOADING',
}
