export enum DRAWERS {
  ACCOUNT = 'account-drawer',
  JOURNAL = 'journal-drawer',
  EXPENSE = 'expense-drawer',
  BILL = 'bill-drawer',
  INVOICE = 'invoice-detail-drawer',
  RECEIPT = 'receipt-detail-drawer',
  PAYMENT_RECEIVE = 'payment-receive-detail-drawer',
  PAYMENT_MADE = 'payment-made-drawer',
  ESTIMATE = 'estimate-detail-drawer',
  ITEM = 'item-detail-drawer',
  CUSTOMER = 'customer-detail-drawer',
  VENDOR = 'vendor-detail-drawer',
  INVENTORY_ADJUSTMENT = 'inventory-adjustment-drawer',
  CASHFLOW_TRNASACTION = 'cashflow-transaction-drawer',
  QUICK_CREATE_CUSTOMER = 'quick-create-customer',
  QUICK_CREATE_ITEM = 'quick-create-item',
  QUICK_WRITE_VENDOR = 'quick-write-vendor',
  CREDIT_NOTE = 'credit-note-detail-drawer',
  VENDOR_CREDIT = 'vendor-credit-detail-drawer',
  REFUND_CREDIT_NOTE = 'refund-credit-detail-drawer',
  REFUND_VENDOR_CREDIT = 'refund-vendor-detail-drawer',
  WAREHOUSE_TRANSFER = 'warehouse-transfer-detail-drawer',
}
