export const BalanceSheetResponseExample = {
  query: {
    display_columns_type: 'total',
    display_columns_by: 'year',
    from_date: '2025-01-01',
    to_date: '2025-06-16',
    number_format: {
      precision: 2,
      divide_on1000: false,
      show_zero: false,
      format_money: 'total',
      negative_format: 'mines',
    },
    none_zero: false,
    none_transactions: false,
    basis: 'cash',
    account_ids: [],
    percentage_of_column: false,
    percentage_of_row: false,
    previous_period: false,
    previous_period_amount_change: false,
    previous_period_percentage_change: false,
    previous_year: false,
    previous_year_amount_change: false,
    previous_year_percentage_change: false,
  },
  data: [
    {
      name: 'Assets',
      id: 'ASSETS',
      node_type: 'AGGREGATE',
      type: 'AGGREGATE',
      total: {
        amount: -122623,
        formatted_amount: '-$122,623.00',
        currency_code: 'USD',
      },
      children: [
        {
          name: 'Current Asset',
          id: 'CURRENT_ASSETS',
          node_type: 'AGGREGATE',
          type: 'AGGREGATE',
          total: {
            amount: -122623,
            formatted_amount: '-$122,623.00',
            currency_code: 'USD',
          },
          children: [
            {
              name: 'Cash and cash equivalents',
              id: 'CASH_EQUIVALENTS',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: -500,
                formatted_amount: '-$500.00',
                currency_code: 'USD',
              },
              children: [
                {
                  id: 1002,
                  index: 1,
                  name: 'Undeposited Funds',
                  code: '10003',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1003,
                  index: 1,
                  name: 'Petty Cash',
                  code: '10004',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1000,
                  index: 1,
                  name: 'Bank Account',
                  code: '10001',
                  total: {
                    amount: -500,
                    formatted_amount: '-500.00',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1001,
                  index: 1,
                  name: 'Saving Bank Account',
                  code: '10002',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1034,
                  index: null,
                  name: 'Chase - Plaid Checking',
                  code: '',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
              ],
            },
            {
              name: 'Accounts Receivable',
              id: 'ACCOUNTS_RECEIVABLE',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: 0,
                formatted_amount: '$0.00',
                currency_code: 'USD',
              },
              children: [
                {
                  id: 1006,
                  index: 1,
                  name: 'Accounts Receivable (A/R)',
                  code: '10007',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
              ],
            },
            {
              name: 'Inventory',
              id: 'INVENTORY',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: 1000,
                formatted_amount: '$1,000.00',
                currency_code: 'USD',
              },
              children: [
                {
                  id: 1007,
                  index: 1,
                  name: 'Inventory Asset',
                  code: '10008',
                  total: {
                    amount: 1000,
                    formatted_amount: '1,000.00',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
              ],
            },
            {
              name: 'Other current assets',
              id: 'OTHER_CURRENT_ASSET',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: -123123,
                formatted_amount: '-$123,123.00',
                currency_code: 'USD',
              },
              children: [
                {
                  id: 1030,
                  index: 1,
                  name: 'Prepaid Expenses',
                  code: '100010',
                  total: {
                    amount: -123123,
                    formatted_amount: '-123,123.00',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
              ],
            },
          ],
        },
        {
          name: 'Fixed Asset',
          id: 'FIXED_ASSET',
          node_type: 'AGGREGATE',
          type: 'AGGREGATE',
          total: {
            amount: 0,
            formatted_amount: '$0.00',
            currency_code: 'USD',
          },
          children: [
            {
              id: 1004,
              index: 1,
              name: 'Computer Equipment',
              code: '10005',
              total: {
                amount: 0,
                formatted_amount: '',
                currency_code: 'USD',
              },
              node_type: 'ACCOUNT',
              children: [],
            },
            {
              id: 1005,
              index: 1,
              name: 'Office Equipment',
              code: '10006',
              total: {
                amount: 0,
                formatted_amount: '',
                currency_code: 'USD',
              },
              node_type: 'ACCOUNT',
              children: [],
            },
          ],
        },
        {
          name: 'Non-Current Assets',
          id: 'NON_CURRENT_ASSET',
          node_type: 'AGGREGATE',
          type: 'AGGREGATE',
          total: {
            amount: 0,
            formatted_amount: '$0.00',
            currency_code: 'USD',
          },
          children: [],
        },
      ],
    },
    {
      name: 'Liabilities and Equity',
      id: 'LIABILITY_EQUITY',
      node_type: 'AGGREGATE',
      type: 'AGGREGATE',
      total: {
        amount: -122623,
        formatted_amount: '-$122,623.00',
        currency_code: 'USD',
      },
      children: [
        {
          name: 'Liabilities',
          id: 'LIABILITY',
          node_type: 'AGGREGATE',
          type: 'AGGREGATE',
          total: {
            amount: -8700,
            formatted_amount: '-$8,700.00',
            currency_code: 'USD',
          },
          children: [
            {
              name: 'Current Liabilties',
              id: 'CURRENT_LIABILITY',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: -8700,
                formatted_amount: '-$8,700.00',
                currency_code: 'USD',
              },
              children: [
                {
                  id: 1008,
                  index: 1,
                  name: 'Accounts Payable (A/P)',
                  code: '20001',
                  total: {
                    amount: 1300,
                    formatted_amount: '1,300.00',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1013,
                  index: 1,
                  name: 'Tax Payable',
                  code: '20006',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1009,
                  index: 1,
                  name: 'Owner A Drawings',
                  code: '20002',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1010,
                  index: 1,
                  name: 'Loan',
                  code: '20003',
                  total: {
                    amount: -10000,
                    formatted_amount: '-10,000.00',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1011,
                  index: 1,
                  name: 'Opening Balance Liabilities',
                  code: '20004',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1012,
                  index: 1,
                  name: 'Revenue Received in Advance',
                  code: '20005',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
                {
                  id: 1029,
                  index: 1,
                  name: 'Unearned Revenue',
                  code: '50005',
                  total: {
                    amount: 0,
                    formatted_amount: '',
                    currency_code: 'USD',
                  },
                  node_type: 'ACCOUNT',
                  children: [],
                },
              ],
            },
            {
              name: 'Long-Term Liabilities',
              id: 'LOGN_TERM_LIABILITY',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: 0,
                formatted_amount: '$0.00',
                currency_code: 'USD',
              },
              children: [],
            },
            {
              name: 'Non-Current Liabilities',
              id: 'NON_CURRENT_LIABILITY',
              node_type: 'AGGREGATE',
              type: 'AGGREGATE',
              total: {
                amount: 0,
                formatted_amount: '$0.00',
                currency_code: 'USD',
              },
              children: [],
            },
          ],
        },
        {
          name: 'Equity',
          id: 'EQUITY',
          node_type: 'AGGREGATE',
          type: 'AGGREGATE',
          total: {
            amount: -113923,
            formatted_amount: '-$113,923.00',
            currency_code: 'USD',
          },
          children: [
            {
              id: 1014,
              index: 1,
              name: 'Retained Earnings',
              code: '30001',
              total: {
                amount: 0,
                formatted_amount: '',
                currency_code: 'USD',
              },
              node_type: 'ACCOUNT',
              children: [],
            },
            {
              id: 1015,
              index: 1,
              name: 'Opening Balance Equity',
              code: '30002',
              total: {
                amount: 0,
                formatted_amount: '',
                currency_code: 'USD',
              },
              node_type: 'ACCOUNT',
              children: [],
            },
            {
              id: 1016,
              index: 1,
              name: "Owner's Equity",
              code: '30003',
              total: {
                amount: 0,
                formatted_amount: '',
                currency_code: 'USD',
              },
              node_type: 'ACCOUNT',
              children: [],
            },
            {
              id: 1017,
              index: 1,
              name: 'Drawings',
              code: '30003',
              total: {
                amount: 0,
                formatted_amount: '',
                currency_code: 'USD',
              },
              node_type: 'ACCOUNT',
              children: [],
            },
            {
              id: 'NET_INCOME',
              name: 'Net Income',
              node_type: 'NET_INCOME',
              total: {
                amount: -113923,
                formatted_amount: '-$113,923.00',
                currency_code: 'USD',
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
  meta: {
    organization_name: 'BIGCAPITAL, INC',
    base_currency: 'USD',
    date_format: 'DD MMM yyyy',
    is_cost_compute_running: false,
    sheet_name: 'Balance Sheet Statement',
    formatted_as_date: '2025/06/16',
    formatted_date_range: 'As 2025/06/16',
  },
};
