export const AssetMeta = {
  tableName: 'assets',
  fields: [
    { name: 'name', type: 'string' },
    { name: 'code', type: 'string' },
    { name: 'description', type: 'text' },
    { name: 'assetAccountId', type: 'number', relation: 'accounts' },
    { name: 'categoryId', type: 'number', relation: 'items_categories' },
    { name: 'purchasePrice', type: 'number' },
    { name: 'purchaseDate', type: 'date' },
    { name: 'purchaseReference', type: 'string' },
    { name: 'depreciationMethod', type: 'string' },
    { name: 'depreciationRate', type: 'number' },
    { name: 'usefulLifeYears', type: 'number' },
    { name: 'residualValue', type: 'number' },
    { name: 'depreciationStartDate', type: 'date' },
    { name: 'depreciationFrequency', type: 'string' },
    { name: 'depreciationExpenseAccountId', type: 'number', relation: 'accounts' },
    { name: 'accumulatedDepreciationAccountId', type: 'number', relation: 'accounts' },
    { name: 'openingDepreciation', type: 'number' },
    { name: 'currentDepreciation', type: 'number' },
    { name: 'totalDepreciation', type: 'number' },
    { name: 'bookValue', type: 'number' },
    { name: 'status', type: 'string' },
    { name: 'serialNumber', type: 'string' },
    { name: 'location', type: 'string' },
    { name: 'active', type: 'boolean' },
  ],
};
