export enum ERRORS {
  DOCUMENT_LINK_REF_INVALID = 'DOCUMENT_LINK_REF_INVALID',
  DOCUMENT_LINK_ID_INVALID = 'DOCUMENT_LINK_ID_INVALID',
  DOCUMENT_LINK_ALREADY_LINKED = 'DOCUMENT_LINK_ALREADY_LINKED'
}
