// @ts-nocheck
export const ERROR = {
  // Sales Estimates
  ESTIMATE_NUMBER_IS_NOT_UNIQUE: 'ESTIMATE.NUMBER.IS.NOT.UNIQUE',
  SALE_ESTIMATE_NO_IS_REQUIRED: 'SALE_ESTIMATE_NO_IS_REQUIRED',

  // Sales Invoices
  SALE_INVOICE_NUMBER_IS_EXISTS: 'SALE.INVOICE.NUMBER.IS.EXISTS',
  SALE_INVOICE_NO_NOT_UNIQUE: 'SALE_INVOICE_NO_NOT_UNIQUE',
  SALE_ESTIMATE_IS_ALREADY_CONVERTED_TO_INVOICE:
    'SALE_ESTIMATE_IS_ALREADY_CONVERTED_TO_INVOICE',

  // Sales Receipts
  SALE_RECEIPT_NUMBER_NOT_UNIQUE: 'SALE_RECEIPT_NUMBER_NOT_UNIQUE',
  SALE_RECEIPT_NO_IS_REQUIRED: 'SALE_RECEIPT_NO_IS_REQUIRED',

  // Bills
  BILL_NUMBER_EXISTS: 'BILL.NUMBER.EXISTS',
  SALE_INVOICE_NO_IS_REQUIRED: 'SALE_INVOICE_NO_IS_REQUIRED',
  ENTRIES_ALLOCATED_COST_COULD_NOT_DELETED:"ENTRIES_ALLOCATED_COST_COULD_NOT_DELETED",

};
