export const SEARCH_TYPE = 'SEARCH_TYPE' as const;
export const OPEN_SEARCH = 'OPEN_SEARCH' as const;
export const CLOSE_SEARCH = 'CLOSE_SEARCH' as const;
export const UNIVERSAL_SEARCH_SET_RESOURCE_TYPE = 'UNIVERSAL_SEARCH_SET_RESOURCE_TYPE' as const;
export const UNIVERSAL_SEARCH_RESET_RESOURCE_TYPE = 'UNIVERSAL_SEARCH_RESET_RESOURCE_TYPE' as const;
export const UNIVERSAL_SEARCH_SET_ITEM_SELECT = 'UNIVERSAL_SEARCH_SET_ITEM_SELECT' as const;
export const UNIVERSAL_SEARCH_RESET_ITEM_SELECT = 'UNIVERSAL_SEARCH_RESET_ITEM_SELECT' as const;
