export const ExportResources = [
  { value: 'account', text: 'Accounts' },
  { value: 'item', text: 'Items' },
  { value: 'item_category', text: 'Item Categories' },
  { value: 'customer', text: 'Customers' },
  { value: 'vendor', text: 'Vendors' },
  { value: 'manual_journal', text: 'Manual Journal' },
  { value: 'expense', text: 'Expenses' },
  { value: 'sale_invoice', text: 'Invoices' },
  { value: 'sale_estimate', text: ' Estimates' },
  { value: 'sale_receipt', text: 'Receipts' },
  { value: 'payment_receive', text: 'Payments Received' },
  { value: 'credit_note', text: 'Credit Notes' },
  { value: 'bill', text: 'Bills' },
  { value: 'bill_payment', text: 'Bill Payments' },
  { value: 'vendor_credit', text: 'Vendor Credits' },
  { value: 'tax_rate', text: 'Tax Rate' },
];
