export const MANUAL_JOURNALS_TABLE_STATE_SET = 'MANUAL_JOURNALS/TABLE_STATE_SET' as const;
export const MANUAL_JOURNALS_TABLE_STATE_RESET = 'MANUAL_JOURNALS/TABLE_STATE_RESET' as const;
export const MANUAL_JOURNALS_SET_SELECTED_ROWS = 'MANUAL_JOURNALS/SET_SELECTED_ROWS' as const;
