export const VENDORS_TABLE_STATE_SET = 'VENDORS/TABLE_STATE_SET' as const;
export const VENDORS_TABLE_STATE_RESET = 'VENDORS/TABLE_STATE_RESET' as const;
export const VENDORS_SELECTED_ROWS_SET = 'VENDORS/SELECTED_ROWS_SET' as const;
export const VENDORS_SET_SELECTED_ROWS = 'VENDORS/SET_SELECTED_ROWS' as const;
export const VENDORS_RESET_SELECTED_ROWS = 'VENDORS/RESET_SELECTED_ROWS' as const;
