export const ACCOUNTS_TABLE_STATE_SET = 'ACCOUNTS/TABLE_STATE_SET' as const;
export const ACCOUNTS_TABLE_STATE_RESET = 'ACCOUNTS/TABLE_STATE_RESET' as const;
export const ACCOUNTS_SET_SELECTED_ROWS = 'ACCOUNTS/SET_SELECTED_ROWS' as const;
