export enum WorkspacesError {
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  NOT_WORKSPACE_OWNER = 'NOT_WORKSPACE_OWNER',
  WORKSPACE_DELETING = 'WORKSPACE_DELETING',
  CANNOT_DELETE_CURRENT_ORGANIZATION = 'CANNOT_DELETE_CURRENT_ORGANIZATION',
}
