export default {
  PAYMENT_MADE_LIST_SET: 'PAYMENT_MADE_LIST_SET',
  PAYMENT_MADE_DELETE: 'PAYMENT_MADE_DELETE',
  PAYMENT_MADE_SET: 'PAYMENT_MADE_SET',
  PAYMENT_MADE_SET_CURRENT_VIEW: 'PAYMENT_MADE_SET_CURRENT_VIEW',
  PAYMENT_MADE_TABLE_QUERIES_ADD: 'PAYMENT_MADE_TABLE_QUERIES_ADD',
  PAYMENT_MADES_TABLE_LOADING: 'PAYMENT_MADES_TABLE_LOADING',
  PAYMENT_MADES_PAGE_SET: 'PAYMENT_MADES_PAGE_SET',
  PAYMENT_MADES_ITEMS_SET: 'PAYMENT_MADES_ITEMS_SET',
  PAYMENT_MADES_PAGINATION_SET: 'PAYMENT_MADES_PAGINATION_SET',
};
