export const BILLS_TABLE_STATE_SET = 'BILLS/TABLE_STATE_SET' as const;
export const BILLS_TABLE_STATE_RESET = 'BILLS/TABLE_STATE_RESET' as const;
export const BILLS_SET_SELECTED_ROWS = 'BILLS/SET_SELECTED_ROWS' as const;
