import { ACCOUNT_TYPE } from "@/constants";

export const SUPPORTED_EXPENSE_PAYMENT_ACCOUNT_TYPES = [
  ACCOUNT_TYPE.CASH,
  ACCOUNT_TYPE.BANK,
  ACCOUNT_TYPE.CREDIT_CARD,
  ACCOUNT_TYPE.OTHER_CURRENT_ASSET,
  ACCOUNT_TYPE.NON_CURRENT_ASSET,
  ACCOUNT_TYPE.FIXED_ASSET,
];
