export const CREDIT_NOTES_TABLE_STATE_SET = 'CREDIT_NOTES/TABLE_STATE_SET' as const;
export const CREDIT_NOTES_TABLE_STATE_RESET = 'CREDIT_NOTE/TABLE_STATE_RESET' as const;
export const CREDIT_NOTES_SET_SELECTED_ROWS = 'CREDIT_NOTES/SET_SELECTED_ROWS' as const;
