export default {
  EXCHANGE_RATE_DATA_TABLE: 'EXCHANGE_RATE_DATA_TABLE',
  EXCHANGE_RATE_DELETE: 'EXCHANGE_RATE_DELETE',
  EXCHANGE_RATE_LIST_SET: 'EXCHANGE_RATE_LIST_SET',
  CLEAR_EXCHANGE_RATE_FORM_ERRORS: 'CLEAR_EXCHANGE_RATE_FORM_ERRORS',
  ExchangeRates_TABLE_QUERIES_ADD: 'ExchangeRates_TABLE_QUERIES_ADD',
  EXCHANGE_RATE_TABLE_LOADING:'EXCHANGE_RATE_TABLE_LOADING'
};
