FROM rabbitmq

COPY scripts /root/scripts/

ARG MANAGEMENT=false
ARG FEDERATION=false
ARG RABBITMQ_DEFAULT_USER=guest
ARG RABBITMQ_DEFAULT_PASS=guest

ENV MANAGEMENT=$MANAGEMENT
ENV FEDERATION=$FEDERATION
ENV RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
ENV RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS

RUN /bin/bash /root/scripts/build-rabbitmq.sh
