
exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('accounts').del()
    .then(() => {
      // Inserts seed entries
      return knex('accounts').insert([
        {
          id: 1,
          name: 'Petty Cash',
          account_type_id: 2,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 2,
          name: 'Bank',
          account_type_id: 2,
          parent_account_id: null,
          code: '2000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 3,
          name: 'Other Income',
          account_type_id: 7,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 4,
          name: 'Interest Income',
          account_type_id: 7,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 5,
          name: 'Opening Balance',
          account_type_id: 5,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 6,
          name: 'Depreciation Expense',
          account_type_id: 6,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 7,
          name: 'Interest Expense',
          account_type_id: 6,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 8,
          name: 'Payroll Expenses',
          account_type_id: 6,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 9,
          name: 'Other Expenses',
          account_type_id: 6,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 10,
          name: 'Accounts Receivable',
          account_type_id: 8,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 11,
          name: 'Accounts Payable',
          account_type_id: 9,
          parent_account_id: null,
          code: '1000',
          description: '',
          active: 1,
          index: 1,
          predefined: 1,
        },
        {
          id: 12, 
          name: 'Cost of Goods Sold (COGS)',
          account_type_id: 12,
          predefined: 1,
          parent_account_id: null,
          index: 1,
          active: 1,
          description: 1,
        },
        {
          id: 13, 
          name: 'Inventory Asset',
          account_type_id: 14,
          predefined: 1,
          parent_account_id: null,
          index: 1,
          active: 1,
          description: '',
        },
        {
          id: 14,
          name: 'Sales of Product Income',
          account_type_id: 7,
          predefined: 1,
          parent_account_id: null,
          index: 1,
          active: 1,
          description: '',
        }
      ]);
    });
};
