export const PAYMENT_RECEIVES_TABLE_STATE_SET = 'PAYMENT_RECEIVES/TABLE_STATE_SET' as const;
export const PAYMENT_RECEIVES_TABLE_STATE_RESET = 'PAYMENT_RECEIVES/TABLE_STATE_RESET' as const;
export const PAYMENT_RECEIVES_SET_SELECTED_ROWS = 'PAYMENT_RECEIVES/SET_SELECTED_ROWS' as const;
