// Query key constants
export const SETTING = 'SETTING';
export const SETTING_INVOICES = 'SETTING_INVOICES';
export const SETTING_ESTIMATES = 'SETTING_ESTIMATES';
export const SETTING_RECEIPTS = 'SETTING_RECEIPTS';
export const SETTING_PAYMENT_RECEIVES = 'SETTING_PAYMENT_RECEIVES';
export const SETTING_MANUAL_JOURNALS = 'SETTING_MANUAL_JOURNALS';
export const SETTING_ITEMS = 'SETTING_ITEMS';
export const SETTING_ITEM_CATEGORIES = 'SETTING_ITEM_CATEGORIES';
export const SETTING_CASHFLOW = 'SETTING_CASHFLOW';
export const SETTING_SMS_NOTIFICATION = 'SETTING_SMS_NOTIFICATION';
export const SETTING_SMS_NOTIFICATIONS = 'SETTING_SMS_NOTIFICATIONS';
export const SETTING_EDIT_SMS_NOTIFICATION = 'SETTING_EDIT_SMS_NOTIFICATION';
export const SETTING_CREDIT_NOTES = 'SETTING_CREDIT_NOTES';
export const SETTING_VENDOR_CREDITS = 'SETTING_VENDOR_CREDITS';
export const SETTING_WAREHOUSE_TRANSFER = 'SETTING_WAREHOUSE_TRANSFERS';
export const SETTING_BILLS = 'SETTING_BILLS';
export const SETTING_BILL_PAYMENTS = 'SETTING_BILL_PAYMENTS';
export const SETTING_ORGANIZATION = 'SETTING_ORGANIZATION';
export const SETTING_EXPENSES = 'SETTING_EXPENSES';
export const SETTING_ACCOUNTS = 'SETTING_ACCOUNTS';
export const SETTING_CUSTOMERS = 'SETTING_CUSTOMERS';
export const SETTING_VENDORS = 'SETTING_VENDORS';
export const SETTING_CASHFLOW_TRANSACTIONS = 'SETTING_CASHFLOW_TRANSACTIONS';
export const SETTING_PROJECTS = 'SETTING_PROJECTS';
export const SETTING_PROJECT_TASKS = 'SETTING_PROJECT_TASKS';
export const SETTING_TIMESHEETS = 'SETTING_TIMESHEETS';

// Query key factory
export const settingsKeys = {
  all: () => [SETTING] as const,
  invoices: () => [SETTING, SETTING_INVOICES] as const,
  estimates: () => [SETTING, SETTING_ESTIMATES] as const,
  receipts: () => [SETTING, SETTING_RECEIPTS] as const,
  paymentReceives: () => [SETTING, SETTING_PAYMENT_RECEIVES] as const,
  manualJournals: () => [SETTING, SETTING_MANUAL_JOURNALS] as const,
  items: () => [SETTING, SETTING_ITEMS] as const,
  itemCategories: () => [SETTING, SETTING_ITEM_CATEGORIES] as const,
  cashflow: () => [SETTING, SETTING_CASHFLOW] as const,
  creditNotes: () => [SETTING, SETTING_CREDIT_NOTES] as const,
  vendorCredits: () => [SETTING, SETTING_VENDOR_CREDITS] as const,
  warehouseTransfers: () => [SETTING, SETTING_WAREHOUSE_TRANSFER] as const,
  bills: () => [SETTING, SETTING_BILLS] as const,
  billPayments: () => [SETTING, SETTING_BILL_PAYMENTS] as const,
  organization: () => [SETTING, SETTING_ORGANIZATION] as const,
  expenses: () => [SETTING, SETTING_EXPENSES] as const,
  accounts: () => [SETTING, SETTING_ACCOUNTS] as const,
  customers: () => [SETTING, SETTING_CUSTOMERS] as const,
  vendors: () => [SETTING, SETTING_VENDORS] as const,
  cashflowTransactions: () => [SETTING, SETTING_CASHFLOW_TRANSACTIONS] as const,
  projects: () => [SETTING, SETTING_PROJECTS] as const,
  projectTasks: () => [SETTING, SETTING_PROJECT_TASKS] as const,
  timesheets: () => [SETTING, SETTING_TIMESHEETS] as const,
  smsNotifications: () => [SETTING_SMS_NOTIFICATIONS] as const,
  smsNotification: (key: string) => [SETTING_SMS_NOTIFICATIONS, key] as const,
};

// Grouped object for use in components/hooks
export const SettingsQueryKeys = {
  SETTING,
  SETTING_INVOICES,
  SETTING_ESTIMATES,
  SETTING_RECEIPTS,
  SETTING_PAYMENT_RECEIVES,
  SETTING_MANUAL_JOURNALS,
  SETTING_ITEMS,
  SETTING_ITEM_CATEGORIES,
  SETTING_CASHFLOW,
  SETTING_SMS_NOTIFICATION,
  SETTING_SMS_NOTIFICATIONS,
  SETTING_EDIT_SMS_NOTIFICATION,
  SETTING_CREDIT_NOTES,
  SETTING_VENDOR_CREDITS,
  SETTING_WAREHOUSE_TRANSFER,
  SETTING_BILLS,
  SETTING_BILL_PAYMENTS,
  SETTING_ORGANIZATION,
  SETTING_EXPENSES,
  SETTING_ACCOUNTS,
  SETTING_CUSTOMERS,
  SETTING_VENDORS,
  SETTING_CASHFLOW_TRANSACTIONS,
  SETTING_PROJECTS,
  SETTING_PROJECT_TASKS,
  SETTING_TIMESHEETS,
} as const;
