

export default {
  GENERAL_LEDGER_STATEMENT_SET: 'GENERAL_LEDGER_STATEMENT_SET',
  GENERAL_LEDGER_SHEET_LOADING: 'GENERAL_LEDGER_SHEET_LOADING',

  BALANCE_SHEET_STATEMENT_SET: 'BALANCE_SHEET_STATEMENT_SET',
  BALANCE_SHEET_LOADING: 'BALANCE_SHEET_LOADING',

  TRAIL_BALANCE_STATEMENT_SET: 'TRAIL_BALANCE_STATEMENT_SET',
  TRIAL_BALANCE_SHEET_LOADING: 'TRIAL_BALANCE_SHEET_LOADING',

  JOURNAL_SHEET_SET: 'JOURNAL_SHEET_SET',
  JOURNAL_SHEET_LOADING: 'JOURNAL_SHEET_LOADING',

  PROFIT_LOSS_SHEET_SET: 'PROFIT_LOSS_SHEET_SET',
  PROFIT_LOSS_SHEET_LOADING: 'PROFIT_LOSS_SHEET_LOADING',

  RECEIVABLE_AGING_SUMMARY_LOADING: 'RECEIVABLE_AGING_SUMMARY_LOADING',
  RECEIVABLE_AGING_SUMMARY_SET: 'RECEIVABLE_AGING_SUMMARY_SET',
}