export default {
  BALANCE_SHEET: 'BALANCE_SHEET',
  TRIAL_BALANCE_SHEET: 'TRIAL_BALANCE_SHEET',
  JOURNAL: 'JOURNAL',
  GENERAL_LEDGER: 'GENERAL_LEDGER',
  PROFIT_LOSS: 'PROFIT_LOSS',
  AR_AGING_SUMMARY: 'AR_AGING_SUMMARY',
  AP_AGING_SUMMARY: 'AP_AGING_SUMMARY',
  DISPLAY_FILTER_DRAWER_TOGGLE: 'DISPLAY_FILTER_DRAWER_TOGGLE'
};
