export default {
  EXPENSES_LIST_SET: 'EXPENSES_LIST_SET',
  EXPENSE_SET: 'EXPENSE_SET',
  EXPENSE_DELETE: 'EXPENSE_DELETE',
  EXPENSES_BULK_DELETE: 'EXPENSES_BULK_DELETE',
  EXPENSES_SET_CURRENT_VIEW: 'EXPENSES_SET_CURRENT_VIEW',
  EXPENSES_TABLE_QUERIES_ADD:'EXPENSES/TABLE_QUERIES_ADD',
  EXPENSE_PUBLISH: 'EXPENSE_PUBLISH',
  EXPENSES_TABLE_LOADING: 'EXPENSES_TABLE_LOADING',
  EXPENSES_PAGE_SET: 'EXPENSES_PAGE_SET',
  EXPENSES_ITEMS_SET: 'EXPENSES_ITEMS_SET',
  EXPENSES_PAGINATION_SET: 'EXPENSES_PAGINATION_SET',
};
