export default {
  CUSTOMERS_ITEMS_SET: 'CUSTOMERS_ITEMS_SET',
  CUSTOMER_SET: 'CUSTOMER_SET',
  CUSTOMERS_PAGE_SET: 'CUSTOMERS_PAGE_SET',
  CUSTOMERS_TABLE_LOADING: 'CUSTOMERS_TABLE_LOADING',
  CUSTOMERS_TABLE_QUERIES_ADD: 'CUSTOMERS_TABLE_QUERIES_ADD',
  CUSTOMER_DELETE:'CUSTOMER_DELETE',
  CUSTOMERS_BULK_DELETE:'CUSTOMERS_BULK_DELETE'
};
