export const ERRORS = {
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  MULTI_WAREHOUSES_ALREADY_ACTIVATED: 'MULTI_WAREHOUSES_ALREADY_ACTIVATED',
  COULD_NOT_DELETE_ONLY_WAREHOUSE: 'COULD_NOT_DELETE_ONLY_WAREHOUSE',
  WAREHOUSE_CODE_NOT_UNIQUE: 'WAREHOUSE_CODE_NOT_UNIQUE',
  WAREHOUSE_HAS_ASSOCIATED_TRANSACTIONS: 'WAREHOUSE_HAS_ASSOCIATED_TRANSACTIONS'
};