export default {
  MAKE_JOURNAL_ENTRIES: 'MAKE_JOURNAL_ENTRIES',
  MANUAL_JOURNAL_SET: 'MANUAL_JOURNAL_SET',

  MANUAL_JOURNALS_TABLE_LOADING: 'MANUAL_JOURNALS_TABLE_LOADING',
  MANUAL_JOURNALS_PAGE_SET: 'MANUAL_JOURNALS_PAGE_SET',
  MANUAL_JOURNALS_ITEMS_SET: 'MANUAL_JOURNALS_ITEMS_SET',
  MANUAL_JOURNALS_SET_CURRENT_VIEW: 'MANUAL_JOURNALS_SET_CURRENT_VIEW',
  MANUAL_JOURNALS_TABLE_QUERIES_ADD: 'MANUAL_JOURNALS_TABLE_QUERIES_ADD',
  MANUAL_JOURNAL_REMOVE: 'MANUAL_JOURNAL_REMOVE',

  MANUAL_JOURNAL_PUBLISH: 'MANUAL_JOURNAL_PUBLISH',
  MANUAL_JOURNALS_BULK_DELETE: 'MANUAL_JOURNALS_BULK_DELETE',
  MANUAL_JOURNALS_PAGINATION_SET: 'MANUAL_JOURNALS_PAGINATION_SET',

  MANUAL_JOURNAL_NUMBER_CHANGED: 'MANUAL_JOURNAL_NUMBER_CHANGED'
};
