const CUSTOMERS = {
  CUSTOMERS: 'CUSTOMERS',
  CUSTOMER: 'CUSTOMER',
};

const PROJECTS = {
  PROJECT: 'PROJECT',
  PROJECTS: 'PROJECTS',
};

const PROJECT_TASKS ={
  PROJECT_TASKS:'PROJECT_TASKS',
  PROJECT_TASK:'PROJECT_TASK',
}

export default { ...PROJECTS, ...CUSTOMERS,...PROJECT_TASKS };
