export const ERRORS = {
  VENDOR_CREDIT_NOT_FOUND: 'VENDOR_CREDIT_NOT_FOUND',
  VENDOR_CREDIT_ALREADY_OPENED: 'VENDOR_CREDIT_ALREADY_OPENED',
  VENDOR_CREDIT_HAS_NO_REMAINING_AMOUNT:
    'VENDOR_CREDIT_HAS_NO_REMAINING_AMOUNT',
  VENDOR_CREDIT_APPLY_TO_BILLS_NOT_FOUND:
    'VENDOR_CREDIT_APPLY_TO_BILLS_NOT_FOUND',
  BILLS_HAS_NO_REMAINING_AMOUNT: 'BILLS_HAS_NO_REMAINING_AMOUNT',
  VENDOR_CREDIT_HAS_REFUND_TRANSACTIONS:
    'VENDOR_CREDIT_HAS_REFUND_TRANSACTIONS',
  VENDOR_CREDIT_HAS_APPLIED_BILLS: 'VENDOR_CREDIT_HAS_APPLIED_BILLS',
};
