export default {
  MAKE_JOURNAL_ENTRIES: 'MAKE_JOURNAL_ENTRIES',
  MANUAL_JOURNALS_TABLE_LOADING: 'MANUAL_JOURNALS_TABLE_LOADING',
  MANUAL_JOURNALS_PAGE_SET: 'MANUAL_JOURNALS_PAGE_SET',
  MANUAL_JOURNALS_DATA_TABLE: 'MANUAL_JOURNALS_DATA_TABLE',
  MANUAL_JOURNALS_ITEMS_SET: 'MANUAL_JOURNALS_ITEMS_SET',
  MANUAL_JOURNALS_SET_CURRENT_VIEW: 'MANUAL_JOURNALS_SET_CURRENT_VIEW',
  MANUAL_JOURNALS_TABLE_QUERIES_ADD: 'MANUAL_JOURNALS_TABLE_QUERIES_ADD',
  MANUAL_JOURNAL_DELETE: 'MANUAL_JOURNAL_DELETE',
};
